# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Download and cache dependencies for "/dev"
      - restore_cache:
          keys:
            - v1-dependencies-dev-{{ checksum "./dev/package-lock.json" }}
            - v1-dependencies-dev-

      - run: cd dev && npm install

      - save_cache:
          paths:
            - dev/node_modules
          key: v1-dependencies-dev-{{ checksum "./dev/package-lock.json" }}

      # run tests!
      - run: npm test
